
variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/j.de-sousa-p.madies-gender-homophily


stages:          
  - deploy


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  
  environment: production
  script:
    - pwd
    ## Pour lancer l'expérience Otree :
    - $SCRIPT_PATH/start_test $CONFIG_PATH

    ## Pour afficher les logs dans la pipeline :
    - cat $CONFIG_PATH/logs/*.log

    ## Pour arreter l'expérience :
     #- $SCRIPT_PATH/stop_test $CONFIG_PATH

    ## ATTENTION!!! LA LIGNE CI-DESSOUS ECRASERA TOUTES VOS DONNEES!!! MERCI DE LA DECOMMENTER A LA FIN DE L'ETUDE OU UNIQUEMENT SI VOUS SAVEZ CE QUE VOUS FAITES!!
    # - $SCRIPT_PATH/resetdb $CONFIG_PATH

    ## LA LIGNE CI-DESSOUS EFFACE LES LOGS PRECEDENTS, A N'ACTIVER QUE SI CES LOGS EXISTENT
    #- rm $CONFIG_PATH/logs/output*.log
